#!perl

{
    inval_name               => 'invalid_name',
    inval_path               => '/sys/invalid/path',
    val_block_class_dev_path => '/sys/block/sda/sda1',
    val_bus_id               => '0000:00:00.0',
    val_bus_name             => 'pci',
    val_class                => 'net',
    val_class_dev            => 'eth0',
    val_class_dev_attr       => 'type',
    val_class_dev_path       => '/sys/class/net/eth0',
    val_dev_attr             => 'vendor',
    val_dev_path             => '/sys/devices/pci0000:00/0000:00:00.0',
    val_drv_attr_name        => 'new_id',
    val_drv_bus_name         => 'pci',
    val_drv_name             => 'tg3',
    val_drv_path             => '/sys/bus/pci/drivers/tg3',
    val_file_path            => '/sys/block/sda/dev',
    val_mod_attr_name        => 'refcnt',
    val_mod_name             => 'usbcore',
    val_mod_parm             => 'blinkenlights',
    val_mod_path             => '/sys/module/usbcore',
    val_mod_section          => '__versions',
    val_write_attr_path      => '/sys/class/net/eth0/tx_queue_len',
}
